services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      # - NODE_ENV=development
      - USE_CHOKIDAR_POLLING=true
    ports:
      - "3000:3000"     # Web app
      # - "35729:35729"   # LiveReload
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
      # - ./app_files/database/database.db:/usr/src/app/database/database.db # Correctly bind host DB file
    working_dir: /usr/src/app
    command: npm run dev

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      # - /app/node_modules
    working_dir: /app
    command: npm start